// Code generated by hero.
// source: imgserver/template/dashboard.html
// DO NOT EDIT!
package template

import "bytes"

func DashboardIndex(buffer *bytes.Buffer) {
	buffer.WriteString(`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello World!</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    `)
	buffer.WriteString(`<script>
var IMGSERVER_URL = 'http://localhost:3001'
var API_URL = 'http://localhost:3001/api'
function submitLogin(data, callback) {
  axios.post(API_URL + '/user/login', data)
  .then(function (response) {
    callback(response.data)
    console.log(response.data);
  })
  .catch(function (error) {
    callback({status: false, message: error})
  })
}
function logout(e){
  e.preventDefault();
  Cookies.remove('user');
  window.location.replace("/");
}
document.addEventListener('DOMContentLoaded', function() {

  var userView = ` + "`" + `
    <div>
      test@gmail.com
      <a href="/" id="logout" onclick="logout(event)">Logout</a>
    </div>
  ` + "`" + `;

  var registerLoginButtons = ` + "`" + `
    <a class="button is-primary" href="/signup">
      <strong>Sign up</strong>
    </a>
    <a class="button is-light"  href="/login">
      Log in
    </a>
  ` + "`" + `
  if (Cookies.get('user')){
    document.querySelector('.nav-top-left').innerHTML = userView;
    let logout = document.querySelector("#logout");
  } else {
    document.querySelector('.nav-top-left').innerHTML = registerLoginButtons;
  }
})

function getFilesForPage(page, callback) {
  var user = JSON.parse(Cookies.get('user'));
  let config = {
    headers: {
      Authorization: 'Bearer ' + user.account.token,
    }
  }
  axios.get(API_URL + '/files/page/' + page, config)
  .then(function (response) {
    callback(response.data)
  })
  .catch(function (error) {
    callback({status: false, message: error})
  })
}
function getFileVersionsForPage(master, page, callback) {
  var user = JSON.parse(Cookies.get('user'));
  let config = {
    headers: {
      Authorization: 'Bearer ' + user.account.token,
    }
  }
  axios.get(API_URL + '/file/'+master+'/versions/page/' + page, config)
  .then(function (response) {
    callback(response.data)
  })
  .catch(function (error) {
    callback({status: false, message: error})
  })
}
function getUserName(){
  if (Cookies.get('user')){
    var user = JSON.parse(Cookies.get('user'));
    return user.account.username;
  }
  return '';
}
</script>
`)
	buffer.WriteString(`
<style>
  .bd-index-header{
    text-align: center;
  }
  .is-primary{
    background-color: #0071d1 !important;
  }
  .get-started {
    text-align: center;
  }
  .html-tag {
    color: #0071d1;
  }
  .html-attribute{
    color: orange;
  }
  .url-modifiers{
    font-weight: bold;
  }
  /*.container {
    padding: 3rem;
  }*/
  .bd-main-container {
  }

  .bd-lead {
    position: relative;
    margin-left: -3rem;
    padding: 3rem;
  }
  .bd-side {
    padding: 3rem 0 3rem 1.5rem;
    position: relative;
  }
  .footer{
    background-color: white;
  }

  /*.articles li a {
    color: #363636;
    text-decoration: underline;
  }*/
  .articles li a.is-active {
    font-weight: bold;
    text-decoration-color: #3273dc;
  }
  .bd-main{
    padding: 0 3rem;
    overflow: hidden;
    position: relative;
  }

  .bd-side-background{
    bottom: 0;
    left: 50%;
    position: absolute;
    right: 0;
    top: 0;
    background-color: #fafafa;
  }
  .bd-side-background{
    background-color: white;
  }
  @media screen and (max-width:1087px) {
     .bd-lead,.bd-side {
      padding:1.5rem
     }
  }
  @media screen and (max-width:1087px) {
   .bd-side-background {
    display:none
   }
  }
@media screen and (min-width:1088px) {
   .bd-duo {
    display:flex
   }
   .bd-lead {
    background-color:#fff;
    overflow:hidden;
    flex-grow:1;
    flex-shrink:1
   }
   .bd-side {
    flex:0 0 calc(10.5rem + 1.5rem);
   }
 }
 @media screen and (min-width:1088px) {
 .bd-main {
  padding:0 3rem
 }
 .bd-lead {
  margin-left:-3rem;
  padding:3rem
 }
 .bd-lead:last-child {
  margin-right:-3rem
 }
 .bd-side {
  padding:3rem 0 3rem 1.5rem
 }
}
@media screen and (min-width:1088px) {
 .bd-duo {
  display:flex
 }
 .bd-lead {
  background-color:#fff;
  overflow:hidden;
  flex-grow:1;
  flex-shrink:1
 }
 .bd-side {
  flex:0 0 calc(10.5rem + 1.5rem);
 }
}
</style>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    var currentLocation = window.location.toString();
    var active = currentLocation.substr(currentLocation.lastIndexOf('/') + 1);
    if (active) {
      var navItem = document.querySelector('.articles li a#' + active);
      if (navItem) {
        navItem.classList.add('is-active');
        var current_article =  document.querySelector('#current-article');
        var route_name = {
          'documentation' : 'Getting Started',
          'upload-image': 'Upload Image',
          'modify-image': 'Modify Image',
        }
        current_article.text = route_name[active]
        current_article.href = '/documentation' + active === 'documentation' ? '' : active
      }
    }

  }, false);
</script>
</head>
<body>
 `)
	buffer.WriteString(`<nav class="navbar  has-shadow is-spaced" role="navigation" aria-label="main navigation">
<div class="container">
<div class="navbar-brand">
<!--<a class="navbar-item" href="https://bulma.io">
  <img src="" width="112" height="28">
</a>-->

<a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
  <span aria-hidden="true"></span>
  <span aria-hidden="true"></span>
  <span aria-hidden="true"></span>
</a>
</div>
<div id="navbarBasicExample" class="navbar-menu">
<div class="navbar-start">
  <a class="navbar-item" href="/">
    Home
  </a>
  <a class="navbar-item" href="/documentation">
    Documentation
  </a>
  <a class="navbar-item" href="/dashboard">
    Dashboard
  </a>
</div>
<div class="navbar-end">
  <div class="navbar-item">
    <div class="buttons nav-top-left">
    </div>
  </div>
</div>
</div>
</div>
</nav>
`)
	buffer.WriteString(`
<script>
if (!Cookies.get('user')){
  window.location.replace("/login");
}
</script>
<main class="bd-main">
<div class="bd-side-background"></div>
<div class="bd-main-container container">
      <div class="bd-duo">
        <div class="bd-lead">
          <nav class="breadcrumb has-bullet-separator" aria-label="breadcrumbs">
          <ul>
            <li><a href="/dashboard">Dashboard</a></li>
          </ul>
        </nav>
`)
	buffer.WriteString(`
<script>
    var userName = getUserName();

    function fileMasterOnClick(e, t) {

      e.preventDefault();
      page = 1;
      if(t === 0){
        var li = document.createElement('li');
        li.innerHTML = ` + "`" + `<a id="${e.target.id}" onclick="fileMasterOnClick(event, 1)">${e.target.text}</a>` + "`" + `;
        document.querySelector('.breadcrumb ul').appendChild(li);
      }

      var loadingView = '<a style="border: 0;" class="button is-loading is-fullwidth is-large">Loading</a>';
      document.querySelector('#dashboard-content').innerHTML = loadingView;
      var fileId = e.target.id;
      getFileVersionsForPage(fileId, page, function(response){
        // console.log(data)
        if (!response.status){
          displayError(response.message);
          return;
        }
        if (response.status && !response.data.length){
          var nothingToSeeView = ` + "`" + `
          <div class="notification">
            There's no version of  this file. <a href="/documentation/modify-image" target="blank">Check this document to see how to modify uploaded images.</a>
          </div>
        ` + "`" + `;
          document.querySelector('#dashboard-content').innerHTML = nothingToSeeView;
          return;
        }

        var userName = getUserName();
        var itemsListView = ` + "`" + `` + "`" + `;
        for (var i =0; i < response.data.length; i+=1) {
          var item = response.data[i];
          itemsListView += createVersionItem(item, userName)
        }

        var listView = ` + "`" + `
          <table class="table">
            <tbody>
             ${itemsListView}
          </table>
        ` + "`" + `
        if (response.data.length === 20){
          listView += ` + "`" + `
            <a id="${fileId}" class="button is-white" onclick=loadVersions(event)>Load more</a>
          ` + "`" + `
        }
      document.querySelector('#dashboard-content').innerHTML = listView;

      })
    }

    function displayError(message){
      var errorView = ` + "`" + `
      <div class="notification is-danger">
        ${message}
          <br/>
         <a class="button is-small" href="/dashboard">Retry</a>
      </div>
      ` + "`" + `
      document.querySelector('#dashboard-content').innerHTML = errorView;
    }

    var page = 1;

    function createItem(item, userName){
      return ` + "`" + `
          <tr>
            <td><a id="${item.ID}" onclick="fileMasterOnClick(event, 0)">${item.name}</a></td>
            <td>${item.CreatedAt}</td>
            <td><a class="button is-text" target="_blank" href="${IMGSERVER_URL}/user/${userName}/resource/${item.name}">View</a></td>
            <td><a class="button is-text" style="background: white; color:#ff3860">Delete</a></td>
          </tr>
          ` + "`" + `
    }

    function createVersionItem(item, userName){
      return ` + "`" + `
          <tr>
            <td>${item.name}</td>
            <td>${item.operations}</td>
            <td>${item.CreatedAt}</td>
            <td><a class="button is-text" target="_blank" href="${IMGSERVER_URL}/user/${userName}/modifiers/${item.operations}/resource/${item.name}">View</a></td>
            <td><a class="button is-text" style="background: white; color:#ff3860">Delete</a></td>
          </tr>
          ` + "`" + `
    }

    function loadVersions(e){
        e.preventDefault();
        page += 1;
        e.target.classList.add('is-loading');
        getFileVersionsForPage(e.target.id, page, function(response){
          if (response.data && response.data.length) {
            var itemsListView = ` + "`" + `` + "`" + `;
            for (var i =0; i < response.data.length; i+=1) {
              var item = response.data[i];
              itemsListView += createVersionItem(item, userName)
            }
            document.querySelector('table tbody').innerHTML += itemsListView
            e.target.classList.remove('is-loading');
          }
          if (response.data.length != 20) {
            e.target.remove();
          }
        })
    }

    function loadMoreMasters(e){
        e.preventDefault();
        page += 1;
        e.target.classList.add('is-loading');
        getFilesForPage(page, function(response){
          if (response.data && response.data.length) {
            var itemsListView = ` + "`" + `` + "`" + `;
            for (var i =0; i < response.data.length; i+=1) {
              var item = response.data[i];
              itemsListView += createItem(item, userName)
            }
            document.querySelector('table tbody').innerHTML += itemsListView
            e.target.classList.remove('is-loading');
          }

          if (response.data.length != 20) {
            e.target.remove();
          }

        })
    }

    document.addEventListener('DOMContentLoaded', function() {

      var li = document.createElement('li');
      li.innerHTML = '<a href="/dashboard">Objects</a>'
      document.querySelector('.breadcrumb ul').appendChild(li);

      getFilesForPage(page, function(response){
        if (!response.status){
          displayError(response.message);
          return;
        }

        if (page == 1 && response.status && !response.data.length){
          var nothingToSeeView = ` + "`" + `
          <div class="notification">
            Bucket is empty. <a href="/documentation/upload-image" target="blank">Check this document to see how to upload images.</a>
          </div>
        ` + "`" + `;
          document.querySelector('#dashboard-content').innerHTML = nothingToSeeView;
          return;
        }
        var itemsListView = ` + "`" + `` + "`" + `;
        for (var i =0; i < response.data.length; i+=1) {
          var item = response.data[i];
          itemsListView +=  createItem(item, userName)
        }

        var listView = ` + "`" + `
          <table class="table">
            <tbody>
             ${itemsListView}
          </table>
        ` + "`" + `
        if (response.data.length === 20){
          listView += ` + "`" + `
            <a class="button is-white" onclick=loadMoreMasters(event)>Load more</a>
          ` + "`" + `
        }
      document.querySelector('#dashboard-content').innerHTML = listView;
      })
    })
</script>
<p class="title">
  Uploaded images
</p>
  <hr style="margin: 0 0 3rem;">
<div id="dashboard-content">
  <a style="border: 0;" class="button is-loading is-fullwidth is-large">Loading</a>
</div>
`)
	buffer.WriteString(`</div>
<aside class="bd-side">
  <nav class="" aria-label="">
<ul class="articles">
  <li><a href="/dashboard">Dashboard</a></li>
  <li><a href="/dashboard/metrics">Metrics</a></li>
<li><a href="/dashboard/settings">Settings</a></li>
</ul>
</nav>
</aside>
</div>
</div>
</main>
`)
	buffer.WriteString(`<footer class="footer">
  <div class="content has-text-centered">
    <p>
      © 2018 foo
    </p>
  </div>
</footer>
</body>
</html>
`)

}
