// Code generated by hero.
// source: imgserver/template/gettingStarted.html
// DO NOT EDIT!
package template

import "bytes"

func GettingStartedIndex(buffer *bytes.Buffer) {
	buffer.WriteString(`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <style>

    </body>
</html>
<style>
  .bd-index-header{
    text-align: center;
  }
  .is-primary{
    background-color: #0071d1 !important;
  }
  .get-started {
    text-align: center;
  }
  .html-tag {
    color: #0071d1;
  }
  .html-attribute{
    color: orange;
  }
  .url-modifiers{
    font-weight: bold;
  }

  .container {
    padding: 3rem;
  }
  .bd-main-container {
  }
  .bd-duo {
    display: flex;
  }
  .bd-lead {
    position: relative;
    margin-left: -3rem;
    padding: 3rem;
    background-color: #fff;
    overflow: hidden;
    flex-grow: 1;
    flex-shrink: 1;
  }
  .bd-side {
    padding: 3rem 0 3rem 1.5rem;
    flex: 0 0 calc(10.5rem + 1.5rem);
    position: relative;
  }
  .footer{
    background-color: white;
  }

  /*.articles li a {
    color: #363636;
    text-decoration: underline;
  }*/
  .articles li a.is-active {
    font-weight: bold;
    text-decoration-color: #3273dc;
  }
</style>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    var currentLocation = window.location.toString();
    var active = currentLocation.substr(currentLocation.lastIndexOf('/') + 1);
    var navItem = document.querySelector('.articles li a#' + active);
    navItem.classList.add('is-active');
    var current_article =  document.querySelector('#current-article');
    var route_name = {
      'documentation' : 'Getting Started',
      'upload-image': 'Upload Image',
      'modify-image': 'Modify Image',
    }
    current_article.text = route_name[active]
    current_article.href = '/documentation' + active === 'documentation' ? '' : active
  }, false);
</script>
</head>
<body>
 `)
	buffer.WriteString(`<nav class="navbar is-light" role="navigation" aria-label="main navigation">
<div class="navbar-brand">
<a class="navbar-item" href="https://bulma.io">
  <img src="" width="112" height="28">
</a>

<a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
  <span aria-hidden="true"></span>
  <span aria-hidden="true"></span>
  <span aria-hidden="true"></span>
</a>
</div>
<div id="navbarBasicExample" class="navbar-menu">
<div class="navbar-start">
  <a class="navbar-item" href="/">
    Home
  </a>
  <a class="navbar-item" href="/documentation">
    Documentation
  </a>
</div>
<div class="navbar-end">
  <div class="navbar-item">
    <div class="buttons">
      <a class="button is-primary">
        <strong>Sign up</strong>
      </a>
      <a class="button is-light">
        Log in
      </a>
    </div>
  </div>
</div>
</div>
</nav>
`)
	buffer.WriteString(`

    <div class="bd-main-container container">
      <nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><a href="/">Home</a></li>
    <li><a href="/documentation">Documentation</a></li>
    <li><a href="/documentation" id="current-article">Getting Started</a></li>
  </ul>
</nav>
      <div class="bd-duo">
        <div class="bd-lead">
`)
	buffer.WriteString(`
<h1 class="title">Getting Started</h1>
<p class="subtitle is-6">
      A simple <strong>container</strong> to center your content horizontally
  </p>
  <hr style="margin: 0 0 3rem;">
  <div class="bd-example">
<div class="content is-small">
<h1>Hello World</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla accumsan, metus ultrices eleifend gravida, nulla nunc varius lectus, nec rutrum justo nibh eu lectus. Ut vulputate semper dui. Fusce erat odio, sollicitudin vel erat vel, interdum mattis neque.</p>
<h2>Second level</h2>
<p>Curabitur accumsan turpis pharetra <strong>augue tincidunt</strong> blandit. Quisque condimentum maximus mi, sit amet commodo arcu rutrum id. Proin pretium urna vel cursus venenatis. Suspendisse potenti. Etiam mattis sem rhoncus lacus dapibus facilisis. Donec at dignissim dui. Ut et neque nisl.</p>
<ul>
<li>In fermentum leo eu lectus mollis, quis dictum mi aliquet.</li>
<li>Morbi eu nulla lobortis, lobortis est in, fringilla felis.</li>
<li>Aliquam nec felis in sapien venenatis viverra fermentum nec lectus.</li>
<li>Ut non enim metus.</li>
</ul>
</div>
</div>
`)
	buffer.WriteString(`        </div>
        <aside class="bd-side">
          <nav class="" aria-label="">
      <ul class="articles">
        <li><a href="/documentation" id="documentation">Introduction</a></li>
        <li><a href="/documentation/upload-image" id="upload-image">Upload Image</a></li>
        <li><a href="/documentation/modify-image" id="modify-image">Modify Images</a></li>
      </ul>
    </nav>
        </aside>
      </div>
    </div>
`)
	buffer.WriteString(`<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>Bulma</strong> by <a href="https://jgthms.com">Jeremy Thomas</a>. The source code is licensed
      <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
      is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
    </p>
  </div>
</footer>
</body>
</html>
`)

}
