// Code generated by hero.
// source: imgserver/template/homeIndex.html
// DO NOT EDIT!
package template

import "bytes"

func HomeIndex(buffer *bytes.Buffer) {
	buffer.WriteString(`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <style>

    </body>
</html>
<style>
  .bd-index-header{
    text-align: center;
  }
  .is-primary{
    background-color: #0071d1 !important;
  }
  .get-started {
    text-align: center;
  }
  .html-tag {
    color: #0071d1;
  }
  .html-attribute{
    color: orange;
  }
  .url-modifiers{
    font-weight: bold;
  }
</style>
</head>
<body>
 `)
	buffer.WriteString(`<nav class="navbar is-light" role="navigation" aria-label="main navigation">
<div class="navbar-brand">
<a class="navbar-item" href="https://bulma.io">
  <img src="" width="112" height="28">
</a>

<a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
  <span aria-hidden="true"></span>
  <span aria-hidden="true"></span>
  <span aria-hidden="true"></span>
</a>
</div>

<div id="navbarBasicExample" class="navbar-menu">
<div class="navbar-start">
  <a class="navbar-item">
    Home
  </a>

  <a class="navbar-item">
    Documentation
  </a>
  <a class="navbar-item">
    Dashboard
  </a>

</div>

<div class="navbar-end">
  <div class="navbar-item">
    <div class="buttons">
      <a class="button is-primary">
        <strong>Sign up</strong>
      </a>
      <a class="button is-light">
        Log in
      </a>
    </div>
  </div>
</div>
</div>
</nav>
`)
	buffer.WriteString(`
    Hello world!
`)

	buffer.WriteString(`
</body>
</html>
`)

}
