// Code generated by hero.
// source: imgserver/template/login.html
// DO NOT EDIT!
package template

import "bytes"

func LoginIndex(buffer *bytes.Buffer) {
	buffer.WriteString(`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello World!</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    `)
	buffer.WriteString(`<script>
var IMGSERVER_URL = 'http://localhost:3001'
var API_URL = 'http://localhost:3001/api'
function submitLogin(data, callback) {
  axios.post(API_URL + '/user/login', data)
  .then(function (response) {
    callback(response.data)
    console.log(response.data);
  })
  .catch(function (error) {
    callback({status: false, message: error})
  })
}
function logout(e){
  e.preventDefault();
  Cookies.remove('user');
  window.location.replace("/");
}
document.addEventListener('DOMContentLoaded', function() {

  var username = getUserName();
  var userView = ` + "`" + `
    <div>
      ${username}
      <a href="/" id="logout" onclick="logout(event)">Logout</a>
    </div>
  ` + "`" + `;

  var registerLoginButtons = ` + "`" + `
    <a class="button is-primary" href="/signup">
      <strong>Sign up</strong>
    </a>
    <a class="button is-light"  href="/login">
      Log in
    </a>
  ` + "`" + `
  if (Cookies.get('user')){
    document.querySelector('.nav-top-left').innerHTML = userView;
    let logout = document.querySelector("#logout");
  } else {
    document.querySelector('.nav-top-left').innerHTML = registerLoginButtons;
  }
})

function getFilesForPage(page, callback) {
  var user = JSON.parse(Cookies.get('user'));
  let config = {
    headers: {
      Authorization: 'Bearer ' + user.account.token,
    }
  }
  axios.get(API_URL + '/files/page/' + page, config)
  .then(function (response) {
    callback(response.data)
  })
  .catch(function (error) {
    callback({status: false, message: error})
  })
}
function getFileVersionsForPage(master, page, callback) {
  var user = JSON.parse(Cookies.get('user'));
  let config = {
    headers: {
      Authorization: 'Bearer ' + user.account.token,
    }
  }
  axios.get(API_URL + '/file/'+master+'/versions/page/' + page, config)
  .then(function (response) {
    callback(response.data)
  })
  .catch(function (error) {
    callback({status: false, message: error})
  })
}
function getUserName(){
  if (Cookies.get('user')){
    var user = JSON.parse(Cookies.get('user'));
    return user.account.username;
  }
  return '';
}
function getSettings(callback) {
  var user = JSON.parse(Cookies.get('user'));
  let config = {
    headers: {
      Authorization: 'Bearer ' + user.account.token,
    }
  }
  axios.get(API_URL + '/user/me', config)
  .then(function (response) {
    callback(response.data);
  })
  .catch(function (error) {
    callback({status: false, message: error});
  })
}

function createDomain(data, callback) {
  var user = JSON.parse(Cookies.get('user'));
  let config = {
    headers: {
      Authorization: 'Bearer ' + user.account.token,
    }
  }
  axios.post(API_URL + '/domains', data, config)
  .then(function (response) {
    callback(response.data);
  })
  .catch(function (error) {
    callback({status: false, message: error});
  })
}

function deleteDomain(data, callback) {
  var user = JSON.parse(Cookies.get('user'));
  let config = {
    headers: {
      Authorization: 'Bearer ' + user.account.token,
    }
  }
  axios.delete(API_URL + '/domains/' + data, config)
  .then(function (response) {
    callback(response.data);
  })
  .catch(function (error) {
    callback({status: false, message: error});
  })
}

function deleteFile(data, callback) {
  var user = JSON.parse(Cookies.get('user'));
  let config = {
    headers: {
      Authorization: 'Bearer ' + user.account.token,
    }
  }
  axios.delete(API_URL + '/files/' + data, config)
  .then(function (response) {
    callback(response.data);
  })
  .catch(function (error) {
    callback({status: false, message: error});
  })
}




/**
 * RegExps.
 * A URL must match #1 and then at least one of #2/#3.
 * Use two levels of REs to avoid REDOS.
 */
// Credits https://github.com/segmentio/is-url/blob/master/index.js
var protocolAndDomainRE = /^(?:\w+:)?\/\/(\S+)$/;

var localhostDomainRE = /^localhost[\:?\d]*(?:[^\:?\d]\S*)?$/
var nonLocalhostDomainRE = /^[^\s\.]+\.\S{2,}$/;

/**
 * Loosely validate a URL ` + "`" + `string` + "`" + `.
 *
 * @param {String} string
 * @return {Boolean}
 */

function isUrl(string){
  if (typeof string !== 'string') {
    return false;
  }

  var match = string.match(protocolAndDomainRE);
  if (!match) {
    return false;
  }

  var everythingAfterProtocol = match[1];
  if (!everythingAfterProtocol) {
    return false;
  }

  if (localhostDomainRE.test(everythingAfterProtocol) ||
      nonLocalhostDomainRE.test(everythingAfterProtocol)) {
    return true;
  }

  return false;
}
</script>
`)
	buffer.WriteString(`
<style>
  .bd-index-header{
    text-align: center;
  }
  .is-primary{
    background-color: #0071d1 !important;
  }
  .get-started {
    text-align: center;
  }
  .html-tag {
    color: #0071d1;
  }
  .html-attribute{
    color: orange;
  }
  .url-modifiers{
    font-weight: bold;
  }
  /*.container {
    padding: 3rem;
  }*/
  .bd-main-container {
  }

  .bd-lead {
    position: relative;
    margin-left: -3rem;
    padding: 3rem;
  }
  .bd-side {
    padding: 3rem 0 3rem 1.5rem;
    position: relative;
  }
  .footer{
    background-color: white;
  }

  /*.articles li a {
    color: #363636;
    text-decoration: underline;
  }*/
  .articles li a.is-active {
    font-weight: bold;
    text-decoration-color: #3273dc;
  }
  .bd-main{
    padding: 0 3rem;
    overflow: hidden;
    position: relative;
  }

  .bd-side-background{
    bottom: 0;
    left: 50%;
    position: absolute;
    right: 0;
    top: 0;
    background-color: #fafafa;
  }
  /* .bd-side-background{
    background-color: white;
  } */
  @media screen and (max-width:1087px) {
     .bd-lead,.bd-side {
      padding:1.5rem
     }
  }
  @media screen and (max-width:1087px) {
   .bd-side-background {
    display:none
   }
  }
@media screen and (min-width:1088px) {
   .bd-duo {
    display:flex
   }
   .bd-lead {
    background-color:#fff;
    overflow:hidden;
    flex-grow:1;
    flex-shrink:1
   }
   .bd-side {
    flex:0 0 calc(10.5rem + 1.5rem);
   }
 }
 @media screen and (min-width:1088px) {
 .bd-main {
  padding:0 3rem
 }
 .bd-lead {
  margin-left:-3rem;
  padding:3rem
 }
 .bd-lead:last-child {
  margin-right:-3rem
 }
 .bd-side {
  padding:3rem 0 3rem 1.5rem
 }
}
@media screen and (min-width:1088px) {
 .bd-duo {
  display:flex
 }
 .bd-lead {
  background-color:#fff;
  overflow:hidden;
  flex-grow:1;
  flex-shrink:1
 }
 .bd-side {
  flex:0 0 calc(10.5rem + 1.5rem);
 }
}
.navbar{
    background-color: #142c5d;
}
.navbar a{
  color: #d2d2d2;
  font-weight: bold;
}
.navbar a:first-child {
  color: white;
}
.navbar a:first-child:hover {
  background-color: transparent;
}
.navbar a:last-child {
  /*color: white;*/
  /*text-decoration: underline;*/
}
.navbar a:last-child:hover {
  color:  #142c5d;
}
.nav-top-left {
  color: white;
}
.nav-top-left #logout {
  color: white;
  font-weight: bold;
}
</style>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    var currentLocation = window.location.toString();
    var active = currentLocation.substr(currentLocation.lastIndexOf('/') + 1);
    if (active) {
      var navItem = document.querySelector('.articles li a#' + active);
      if (navItem) {
        navItem.classList.add('is-active');
        var current_article =  document.querySelector('#current-article');
        var route_name = {
          'documentation' : 'Getting Started',
          'upload-image': 'Upload Image',
          'modify-image': 'Modify Image',
        }
        current_article.text = route_name[active]
        current_article.href = '/documentation' + active === 'documentation' ? '' : active
      }
    }

  }, false);
</script>
</head>
<body>
 `)
	buffer.WriteString(`<nav class="navbar  has-shadow is-spaced" role="navigation" aria-label="main navigation">
<div class="container">
<div class="navbar-brand">
<!--<a class="navbar-item" href="https://bulma.io">
  <img src="" width="112" height="28">
</a>-->

<a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
  <span aria-hidden="true"></span>
  <span aria-hidden="true"></span>
  <span aria-hidden="true"></span>
</a>
</div>
<div id="navbarBasicExample" class="navbar-menu">
<div class="navbar-start">
  <a class="navbar-item">
    imgserver
   </a>
  <a class="navbar-item" href="/">
    Home
  </a>
  <a class="navbar-item" href="/documentation">
    Documentation
  </a>
  <a class="navbar-item" href="/dashboard">
    Dashboard
  </a>
</div>
<div class="navbar-end">
  <div class="navbar-item">
    <div class="buttons nav-top-left">
    </div>
  </div>
</div>
</div>
</div>
</nav>
`)
	buffer.WriteString(`
<script>

  if (Cookies.get('user')){
    window.location.replace("/dashboard");
  }

  document.addEventListener('DOMContentLoaded', function() {
    if (Cookies.get('user')){
      return;
    }
    function validateEmail(email) {
      var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
      return re.test(String(email).toLowerCase());
    }
    function createError(err){
      let paragraph = document.createElement("p");
      let text = document.createTextNode(err ? err : "This field is required!");
      paragraph.appendChild(text);
      paragraph.classList.add('help');
      paragraph.classList.add('is-danger');
      return paragraph;
    }
    let form = document.querySelector('#form')
    let submitButton = form.querySelector("#submit");
    submitButton.onclick = function (e) {
      e.preventDefault();
      var email = form.querySelector("#email");
      var password = form.querySelector("#password");
      if (!email.value.length || !validateEmail(email.value)) {
        email.classList.add('is-danger');

        let emailControl = form.querySelector('.email-control');
        let prevErr = emailControl.querySelector('p.is-danger');
        if (prevErr){
          prevErr.remove();
        }
        let err = createError()
        emailControl.appendChild(err);

        email.onfocus = function() {
          email.classList.remove('is-danger');
          if (err){
            err.remove();
          }
        }
      }
      if (!password.value.length || password.value.length < 6) {
        password.classList.add('is-danger');
        let pwdControl = form.querySelector('.password-control');
        let prevErr = pwdControl.querySelector('p.is-danger');
        if (prevErr){
          prevErr.remove();
        }
        let err = createError();
        pwdControl.appendChild(err);
        password.onfocus = function() {
          password.classList.remove('is-danger');
          if (err){
            err.remove();
          }
        }
      }

      if (email.value.length && password.value.length && validateEmail(email.value)) {
        submitButton.classList.add('is-loading')
        submitLogin({ email: email.value, password: password.value }, function(data){
          submitButton.classList.remove('is-loading')
          if (data.status) {
            Cookies.set('user', data);
            window.location.replace("/dashboard");
          } else {
              let prevErr = form.querySelector('p.is-danger');
              if (prevErr){
                prevErr.remove();
              }
              let err = createError(data.message);
              form.appendChild(err);
          }
        });
      }
    }
  })
</script>
<section class="hero">
  <div class="hero-body">
      <div class="container has-text-centered">
          <div class="column is-4 is-offset-4">
              <h3 class="title">Log in</h3>
              <p class="subtitle">Access your account.</p>
              <div class="box">
                  <form id="form">
                      <div class="field">
                          <div class="control email-control">
                              <input id="email" class="input is-large" type="email" placeholder="Your Email" autofocus="">
                          </div>
                      </div>
                      <div class="field">
                          <div class="control password-control">
                              <input id="password" class="input is-large" type="password" placeholder="Your Password">
                          </div>
                      </div>
                      <!-- <div class="field">
                          <label class="checkbox">
            <input type="checkbox">
            Remember me
          </label>
                      </div> -->
                      <button id="submit" class="button is-block is-info is-large is-fullwidth">Log in</button>
                  </form>
              </div>
              <p class="has-text-grey">
                  <a href="/signup">Sign up</a> &nbsp;·&nbsp;
              </p>
          </div>
      </div>
  </div>
</section>

`)
	buffer.WriteString(`<footer class="footer">
  <div class="content has-text-centered">
    <p>
      © 2018 foo
    </p>
  </div>
</footer>
</body>
</html>
`)

}
