// Code generated by hero.
// source: imgserver/template/modifyImage.html
// DO NOT EDIT!
package template

import "bytes"

func ModifyImageIndex(buffer *bytes.Buffer) {
	buffer.WriteString(`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    `)
	buffer.WriteString(`<script>
var IMGSERVER_URL = 'http://localhost:3001'
var API_URL = 'http://localhost:3001/api'
function submitLogin(data, callback) {
  axios.post(API_URL + '/user/login', data)
  .then(function (response) {
    callback(response.data)
    console.log(response.data);
  })
  .catch(function (error) {
    callback({status: false, message: error})
  })
}
function logout(e){
  e.preventDefault();
  Cookies.remove('user');
  window.location.replace("/");
}
document.addEventListener('DOMContentLoaded', function() {

  var userView = ` + "`" + `
    <div>
      test@gmail.com
      <a href="/" id="logout" onclick="logout(event)">Logout</a>
    </div>
  ` + "`" + `;

  var registerLoginButtons = ` + "`" + `
    <a class="button is-primary" href="/signup">
      <strong>Sign up</strong>
    </a>
    <a class="button is-light"  href="/login">
      Log in
    </a>
  ` + "`" + `
  if (Cookies.get('user')){
    document.querySelector('.nav-top-left').innerHTML = userView;
    let logout = document.querySelector("#logout");
  } else {
    document.querySelector('.nav-top-left').innerHTML = registerLoginButtons;
  }
})

function getFilesForPage(page, callback) {
  var user = JSON.parse(Cookies.get('user'));
  let config = {
    headers: {
      Authorization: 'Bearer ' + user.account.token,
    }
  }
  axios.get(API_URL + '/files/page/' + page, config)
  .then(function (response) {
    callback(response.data)
  })
  .catch(function (error) {
    callback({status: false, message: error})
  })
}
function getFileVersionsForPage(master, page, callback) {
  var user = JSON.parse(Cookies.get('user'));
  let config = {
    headers: {
      Authorization: 'Bearer ' + user.account.token,
    }
  }
  axios.get(API_URL + '/file/'+master+'/versions/page/' + page, config)
  .then(function (response) {
    callback(response.data)
  })
  .catch(function (error) {
    callback({status: false, message: error})
  })
}
function getUserName(){
  if (Cookies.get('user')){
    var user = JSON.parse(Cookies.get('user'));
    return user.account.username;
  }
  return '';
}
</script>
`)
	buffer.WriteString(`
<style>
  .bd-index-header{
    text-align: center;
  }
  .is-primary{
    background-color: #0071d1 !important;
  }
  .get-started {
    text-align: center;
  }
  .html-tag {
    color: #0071d1;
  }
  .html-attribute{
    color: orange;
  }
  .url-modifiers{
    font-weight: bold;
  }
  /*.container {
    padding: 3rem;
  }*/
  .bd-main-container {
  }
  .bd-duo {
    display: flex;
  }
  .bd-lead {
    position: relative;
    margin-left: -3rem;
    padding: 3rem;
    background-color: #fff;
    overflow: hidden;
    flex-grow: 1;
    flex-shrink: 1;
  }
  .bd-side {
    padding: 3rem 0 3rem 1.5rem;
    flex: 0 0 calc(10.5rem + 1.5rem);
    position: relative;
  }
  .footer{
    background-color: white;
  }

  /*.articles li a {
    color: #363636;
    text-decoration: underline;
  }*/
  .articles li a.is-active {
    font-weight: bold;
    text-decoration-color: #3273dc;
  }
  .bd-main{
    padding: 0 3rem;
    overflow: hidden;
    position: relative;
  }

  .bd-side-background{
    bottom: 0;
    left: 50%;
    position: absolute;
    right: 0;
    top: 0;
    background-color: #fafafa;
  }
  .bd-side-background{
    background-color: white;
  }
</style>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    var currentLocation = window.location.toString();
    var active = currentLocation.substr(currentLocation.lastIndexOf('/') + 1);
    if (active) {
      var navItem = document.querySelector('.articles li a#' + active);
      if (navItem) {
        navItem.classList.add('is-active');
        var current_article =  document.querySelector('#current-article');
        var route_name = {
          'documentation' : 'Getting Started',
          'upload-image': 'Upload Image',
          'modify-image': 'Modify Image',
        }
        current_article.text = route_name[active]
        current_article.href = '/documentation' + active === 'documentation' ? '' : active
      }
    }

  }, false);
</script>
</head>
<body>
 `)
	buffer.WriteString(`<nav class="navbar  has-shadow is-spaced" role="navigation" aria-label="main navigation">
<div class="container">
<div class="navbar-brand">
<!--<a class="navbar-item" href="https://bulma.io">
  <img src="" width="112" height="28">
</a>-->

<a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
  <span aria-hidden="true"></span>
  <span aria-hidden="true"></span>
  <span aria-hidden="true"></span>
</a>
</div>
<div id="navbarBasicExample" class="navbar-menu">
<div class="navbar-start">
  <a class="navbar-item" href="/">
    Home
  </a>
  <a class="navbar-item" href="/documentation">
    Documentation
  </a>
  <a class="navbar-item" href="/dashboard">
    Dashboard
  </a>
</div>
<div class="navbar-end">
  <div class="navbar-item">
    <div class="buttons nav-top-left">
    </div>
  </div>
</div>
</div>
</div>
</nav>
`)
	buffer.WriteString(`

<main class="bd-main">
<div class="bd-side-background"></div>
<div class="bd-main-container container">
      <div class="bd-duo">
        <div class="bd-lead">
          <nav class="breadcrumb has-bullet-separator" aria-label="breadcrumbs">
          <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/documentation">Documentation</a></li>
            <li><a href="/documentation" id="current-article">Getting Started</a></li>
          </ul>
        </nav>
`)
	buffer.WriteString(`
<h1 class="title">Modify Image</h1>
<p class="subtitle is-6">
      A simple <strong>container</strong> to center your content horizontally
  </p>
  <hr style="margin: 0 0 3rem;">
  <p>Lorem ipsum</p>
`)
	buffer.WriteString(`        </div>
        <aside class="bd-side">
          <nav class="" aria-label="">
      <ul class="articles">
        <li><a href="/documentation" id="documentation">Introduction</a></li>
        <li><a href="/documentation/upload-image" id="upload-image">Upload Image</a></li>
        <li><a href="/documentation/modify-image" id="modify-image">Modify Images</a></li>
      </ul>
    </nav>
        </aside>
      </div>
    </div>
  </main>
`)
	buffer.WriteString(`<footer class="footer">
  <div class="content has-text-centered">
    <p>
      © 2018 foo
    </p>
  </div>
</footer>
</body>
</html>
`)

}
